openapi: 3.1.0
info:
    title: ""
    version: ""
paths:
    /api/v1/items:
        get:
            operationId: getItems
            parameters:
                -   name: limit
                    in: query
                    required: true
                    schema:
                        type: integer
                        format: int32
                -   name: offset
                    in: query
                    required: true
                    schema:
                        type: integer
                        format: int32
            responses:
                "200":
                    description: crud.v1.Crud.GetItems response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/GetItemsResponse'
        post:
            operationId: createItem
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateItemRequest'
                required: true
            responses:
                "200":
                    description: crud.v1.Crud.CreateItem response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Item'
    /api/v1/items/{id}:
        get:
            operationId: getItem
            parameters:
                -   name: id
                    in: path
                    required: true
                    schema:
                        type: string
            responses:
                "200":
                    description: crud.v1.Crud.GetItem response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Item'
        put:
            operationId: updateItem
            parameters:
                -   name: id
                    in: path
                    required: true
                    schema:
                        type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                name:
                                    type: string
                            required:
                                - name
                required: true
            responses:
                "200":
                    description: crud.v1.Crud.UpdateItem response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Item'
        delete:
            operationId: deleteItem
            parameters:
                -   name: id
                    in: path
                    required: true
                    schema:
                        type: string
            responses:
                "200":
                    description: crud.v1.Crud.DeleteItem response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Empty'
        patch:
            operationId: patchItem
            parameters:
                -   name: id
                    in: path
                    required: true
                    schema:
                        type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                name:
                                    type: string
                required: true
            responses:
                "200":
                    description: crud.v1.Crud.PatchItem response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Item'
components:
    schemas:
        CreateItemRequest:
            type: object
            properties:
                name:
                    type: string
            required:
                - name
        Empty:
            type: object
        GetItemsResponse:
            type: object
            properties:
                items:
                    type: array
                    items:
                        $ref: '#/components/schemas/Item'
                totalCount:
                    type: integer
                    format: int32
            required:
                - items
                - totalCount
        Item:
            type: object
            properties:
                id:
                    type: string
                name:
                    type: string
            required:
                - id
                - name
