openapi: 3.1.0
info:
    title: ""
    version: ""
paths:
    /api/v1/{fooId}/{barId}/{baZId}:
        get:
            operationId: fooMethod
            parameters:
                -   name: baZId
                    in: path
                    required: true
                    schema:
                        type: string
                -   name: barId
                    in: path
                    required: true
                    schema:
                        type: string
                -   name: fooId
                    in: path
                    required: true
                    schema:
                        type: string
            responses:
                "200":
                    description: service.v1.Service.FooMethod response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/FooResponse'
components:
    schemas:
        FooRequest:
            type: object
            properties:
                fooId:
                    type: string
                barId:
                    type: string
                baZId:
                    type: string
        FooResponse:
            type: object
