openapi: 3.1.0
info:
    title: ""
    version: ""
paths:
    /api/v1/{id}:
        put:
            operationId: putMethod
            parameters:
                -   name: id
                    in: path
                    required: true
                    schema:
                        type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                body:
                                    type: string
                required: true
            responses:
                "200":
                    description: service.v1.Service.PutMethod response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Response'
components:
    schemas:
        Request:
            type: object
            properties:
                id:
                    type: string
                body:
                    type: string
        Response:
            type: object
